### ISSUE TITLE
v4 architechture documentation

### ISSUE THREAD

**Issue by techtonik** [pgbovine/OnlinePythonTutor#103]
Will there be some docs on frontend / backend architecture, functions and frame format? Code looks much better organized, but still no entrypoint to start hacking.

**Comment by pgbovine** [comment]
There are already docs for v3/, which people have been using to hack. v4 is still very experimental and just for myself right now. Here are v3 docs:

https://github.com/pgbovine/OnlinePythonTutor/tree/master/v3/docs

**Comment by techtonik** [comment]
Yes, but do you plan to clean up the docs first before start hacking?
