### ISSUE TITLE
AttributeError: type object '_io.StringIO' has no attribute 'StringIO'

### ISSUE THREAD

**Issue by ghost** [pgbovine/OnlinePythonTutor#111]
Hi thanks for the wonderful app that has helped me immensely!

I am trying to run locally. Python 3, Arch, Arm, Chrome.
Have changed bottle_server.py as follows:

from io import StringIO                                                       
22import json                                                                   
23import pg_logger                                                              
24import urllib                                                                 
25# import urllib2

@get('/exec')                                                                 
36def get_exec():                                                               
37  out_s = StringIO.StringIO()    

Everything fires up as expected but on clicking visualize execution the browser reports:

Server error! Your code might be taking too much time to run or using too much memory.

Terminal returns a long string prefixed by an error message:

AttributeError: type object '_io.StringIO' has no attribute 'StringIO'

I am sure that i am doing something dumb but a pointer to what would be helpful!

**Comment by pgbovine** [comment]
look in pg_logger.py to find where i use StringIO -- it probably differs between Py2 and 3, and i just didn't patch it fo Py3. good luck

**Comment by SLeonidV** [comment]
ghost I solved that issue - I changed out_s = StringIO.StringIO()  to  out_s = StringIO()

**Comment by pgbovine** [comment]
Thanks. yes it's a io vs StringIO difference between python 2 and 3

**Comment by ItsPavan** [comment]
@SLeonidV Where did you make that change?

**Comment by SLeonidV** [comment]
ItsPavan , have you read 1st comment from ghost?;-) In bottle_server.py on 37 line out_s = StringIO.StringIO()
