### ISSUE TITLE
Ace code editor sometimes behaves all funky in Internet Explorer :(

### ISSUE THREAD

**Issue by pgbovine** [pgbovine/OnlinePythonTutor#113]
ugh

**Comment by daveagp** [comment]
CodeMirror is amazing not the least because of its logo

**Comment by pgbovine** [comment]
ironically i switched from CM to Ace last year *because* of an important IE-related use case

**Comment by pgbovine** [comment]
fixed! https://github.com/pgbovine/OnlinePythonTutor/commit/aa0a2a969cc7f80921b24aa9b61f02dcc1ee3f23
