### ISSUE TITLE
misoperaciones

### ISSUE THREAD

**Issue by jcjocop** [pgbovine/OnlinePythonTutor#114]
def suma(valor1, valor2, valor3):
    lasuma_es = valor1 + valor2 + valor3
    return lasuma_es

def promedio(lasuma):
    elpromedio_es = lasuma/3.0
    return elpromedio_es

def despedida():
    print ""
    print "fin del programa"

**Comment by pgbovine** [comment]
i have no idea what this means. this is simply a piece of python code. please write a bug report if you would like me to look at it.
