### ISSUE TITLE
Enchancement: Syntax highlight in visualization mode

### ISSUE THREAD

**Issue by dz0** [pgbovine/OnlinePythonTutor#116]
Hi, 

syntax highlighting helps not only while writing code, but also while following.. :)

could use the same colors as in "edit" mode.  would be more consistent and nice :)

**Comment by pgbovine** [comment]
Try live programming mode for now:
http://www.pythontutor.com/live.html#mode=edit

In the future, I hope to merge the two modes so that there's syntax highlighting while running code

**Comment by hcientist** [comment]
Live Programming Mode doesn't support syntax highlighting, but the Java editor does support syntax highlighting, but the Visualize Execution doesn't... what do? reopen with #helpwanted ?
