### ISSUE TITLE
Enhancement: Adding support for trees

### ISSUE THREAD

**Issue by sumit0190** [pgbovine/OnlinePythonTutor#118]
I am trying to add support for visualizing trees with OPT. I generated an execution trace for a sample tree program (it's a huge 1.4mb file with over 75k lines), but that's not too bad I guess. My question is: How do I add the actual visualizations in pytutor.js? It's a huge file, so any pointers on where I could start?

For reference, I intend to visualize trees as shown here http://bl.ocks.org/d3noob/8326869

**Comment by arikrak** [comment]
It would be really cool if people could see their own tree and graph algorithms visualized, as mentioned in the [project ideas](https://github.com/pgbovine/OnlinePythonTutor/blob/b549677f176165be6c86de5a8f11a14448c2b2ea/v3/docs/project-ideas.md#custom-data-structure-visualizations). [Algomation](http://www.algomation.com/algorithm/graph-connected-components-algorithm) does that to a certain extent with JavaScript, but people usually learn Algorithms with Java or Python.

**Comment by techtonik** [comment]
Wow, I was looking for something like Algomation for a long time. As for trees, the http://www.johnnovak.net/twyg/ is one of the tools that allows that.

**Comment by pgbovine** [comment]
yep, these ideas have been noted in https://github.com/pgbovine/OnlinePythonTutor/blob/b549677f176165be6c86de5a8f11a14448c2b2ea/v3/docs/project-ideas.md#custom-data-structure-visualizations

closing for now. probably won't get around to it anytime soon :( great ideas, though!
