### ISSUE TITLE
Escape close round bracket in permalinks.

### ISSUE THREAD

**Issue by jamespjh** [pgbovine/OnlinePythonTutor#123]
http://www.pythontutor.com/visualize.html#code=print+len('Hello')&mode=display&origin=opt-frontend.js&cumulative=false&heapPrimitives=true&textReferences=false&py=2&rawInputLstJSON=%5B%5D&curInstr=0

Is a perfectly valid link.

But is hard to link in some places in Markdown (particularly the IPython notebook) because the link comes out stopping at the first close round bracket.

Interestingly, [Github markdown](http://www.pythontutor.com/visualize.html#code=print+len('Hello') &mode=display&origin=opt-frontend.js&cumulative=false&heapPrimitives=true&textReferences=false&py=2&rawInputLstJSON=%5B%5D&curInstr=0) is fine.

Escaping close round bracket to %29 in the permalinks would make it easier to quickly drop these links into the notebook.

**Comment by pgbovine** [comment]
fixed with https://github.com/pgbovine/OnlinePythonTutor/commit/57d62584d20f6d3375ba5858531b4056d39572d9

please test and make sure it works!

**Comment by jamespjh** [comment]
Validated fix.
