### ISSUE TITLE
Will it  support C++ or Pascal ?

### ISSUE THREAD

**Issue by WPH95** [pgbovine/OnlinePythonTutor#125]
i see V4 had  to support multiple languages .
So i want to know if it will support C++ or pascal in the future ?

**Comment by pgbovine** [comment]
sorry those languages aren't currently in the plans due to technical difficulties of getting them implemented. see my master's thesis for more gory details ;)

http://pgbovine.net/publications/Philip-Guo_Masters-thesis_mixed-level-dynamic-analysis.pdf
