### ISSUE TITLE
Python: Visualization of "pre-computed" values for function parameters with default value

### ISSUE THREAD

**Issue by fjfnaranjo** [pgbovine/OnlinePythonTutor#127]
Hi.

Python evaluates the expression used for default parameters once. It does it when the function is defined and then reuses the same value every time the function is called.

This creates confusion sometimes for newcomers as explained in http://docs.python-guide.org/en/latest/writing/gotchas/#mutable-default-arguments

The python documentation states this behavior in the bolded paragraph start in this documentation section https://docs.python.org/3.4/reference/compound_stmts.html#function-definitions

It will be useful to show newcomers this behavior somehow.

I will attach for consideration an alternative render for the steps two and twelve of this code (Python version 3):

``` python
def append_to(element, to=[]):
    to.append(element)
    return to
my_list = append_to(12)
print(my_list)
my_other_list = append_to(42)
print(my_other_list)
```

![python-tutor-proposal](https://cloud.githubusercontent.com/assets/484198/10036380/2d637e4c-61a7-11e5-8987-5f45eb50caa1.png)

I think the alternative 1 represents better what is happening under the table. Also, I think it represents better where is the data stored. Python docs does not say anything about implementation details, but they explicitly use the term "pre-computed".

Also, I think I overdid this...

**Comment by pgbovine** [comment]
This is very interesting! However, I don't know whether the backend I use exposes this level of detail. Also I'd need to augment the function rendering for this special case, so it might take a lot of work.

It is a good issue and proposal, though, so I'll keep it in mind for the future. Thanks for taking the time to make the drawings! I see what you mean :) Sorry that I probably won't have time to get around to this feature anytime soon, though.

**Comment by fjfnaranjo** [comment]
Thanks for keeping it in mind for the future.

> I don't know whether the backend I use exposes this level of detail

I have been checking on this. Even Python doesn't show this values in the exposed \_\_xxx\_\_ internal members.

In older version of Python, "func_defaults" was available as a member for "function" objects. But today we should use the package inspect for this.

In my current Python 3.3 interpreter ...:

```python
from inspect import getargspec
getargspec(append_to)
```

... after the issue sample code shows:

```ArgSpec(args=['element', 'to'], varargs=None, keywords=None, defaults=([12, 42],))```

If you watch carefully, there is not even a relation between the "defaults" member positions and the "args" member positions.

This way seems reliable across a few Python versions if the default values are at the end:

```python
spec = getargspec(append_to)
default_values = spec.args[-len(spec.defaults):]
defaults = dict(zip(spec.args[-len(spec.defaults):], spec.defaults))
```

> Also I'd need to augment the function rendering for this special case

I think the alternative 1 also wins in this problem. The alternative 2 seems much harder to implement in the rendering side.

**Comment by pgbovine** [comment]
Thanks for the details! i'll keep this issue open. you've been very helpful so far

**Comment by pgbovine** [comment]
@fjfnaranjo -- fixed! https://t.co/d8iN1T5VJ8

**Comment by fjfnaranjo** [comment]
Thanks.

By the way: nice solution for the visualization. Looks neat.
