### ISSUE TITLE
Python pprint on complex and long data structures?

### ISSUE THREAD

**Issue by mayli** [pgbovine/OnlinePythonTutor#128]
Some data structures like Counter is show all content in one line, is it possible to draw it using the pprint.pprint?

http://pythontutor.com/visualize.html#code=import+collections%0Aimport+operator%0A%0Aclass+Solution%3A%0A++++%23+%40param+strs,+a+list+of+strings%0A++++%23+%40return+a+list+of+strings%0A++++def+anagrams(self,+strs%29%3A%0A++++++++table+%3D+collections.defaultdict(list%29%0A++++++++a_z+%3D+'abcdefghijklmnopqrstuvwxyz'%0A++++++++for+s+in+strs%3A%0A++++++++++++c+%3D+collections.Counter(s%2Ba_z%29%0A++++++++++++key+%3D+tuple(%5Bv+for+k,v+in+sorted(c.items(%29,+key%3Doperator.itemgetter(0%29%29%5D%29%0A++++++++++++table%5Bkey%5D.append(s%29%0A++++++++%0A++++++++ret+%3D+%5B%5D%0A++++++++for+value+in+table.values(%29%3A%0A++++++++++++if+len(value%29+%3E+1%3A%0A++++++++++++++++ret.extend(value%29%0A++++++++return+ret&mode=display&origin=opt-frontend.js&cumulative=false&heapPrimitives=false&textReferences=false&py=2&rawInputLstJSON=%5B%5D&curInstr=170&testCasesJSON=%5B%22s+%3D+Solution(%29%5Cnassert+s.anagrams(%5B'apple','appel','abc','ccc','cba'%5D%29+%3D%3D+%5B'apple','appel',+'abc','cba'%5D%5Cn%23+assert+%3Ctest+condition%3E%22%5D

**Comment by pgbovine** [comment]
That's interesting; I'll look into it. Not sure how to specify a custom pretty-print function in a robust way without hard-coding it, though, which I don't want to do.

(Also, a note just for myself: when test cases are provided, they are not visualized by default; one has to go back to Edit mode and then manually visualize the test cases.)

**Comment by pgbovine** [comment]
idea: if this object has a __str__ method that's *not* just the boring object.__str__ method (i don't think straight-up equality comparison works, tho), then try to call it to pretty-print the object.

**Comment by pgbovine** [comment]
fixed!
