### ISSUE TITLE
Parse PCAP file in Python

### ISSUE THREAD

**Issue by thanhthuy1** [pgbovine/OnlinePythonTutor#141]
[slowdownload.zip](https://github.com/pgbovine/OnlinePythonTutor/files/133638/slowdownload.zip)

Hello everyone,

I just start studying Python, and have no more experience about it. And I have a trouble to solve this probem. Please help me.

1. Parse a PCAP file.
2. Sample flows with the size over packets. For each of those flows ouput the first packet into PCAP file.
Treat a flow as a complete conversation/session between 2 hosts.

I am a new one, so I do not know what I should do first to solve this. Please guide me.
Thank you very much.

**Comment by Avatazjoe** [comment]
https://pypi.python.org/pypi/pcap-parser

pip install pcap-parser

**Comment by NamPNQ** [comment]
I don't think this is issue of this project, ask it in python comunity

**Comment by Avatazjoe** [comment]
you may like install virtualbox with kali linux, you will find your way
dealing with pcap files with.
