### ISSUE TITLE
AttributeError: module 'urllib' has no attribute 'request'

### ISSUE THREAD

**Issue by klonuo** [pgbovine/OnlinePythonTutor#147]
When I load IPython extension I get this Exception:

``` pytb
AttributeError                            Traceback (most recent call last)
<ipython-input-3-b40fe6b6a5d5> in <module>()
----> 1 urlopen = urllib.request.urlopen

AttributeError: module 'urllib' has no attribute 'request'
```

I'm running Python 3.5.1

**Comment by techtonik** [comment]
Is it the same for Python 3.4/3.3?

**Comment by klonuo** [comment]
Yes urllib refactor is same for 3.3/3.4/3.5

**Comment by pgbovine** [comment]
the ipython plugin was an old prototype and isn't actively being maintained, closing for now. thanks

**Comment by bkeating** [comment]
Import `urllib.request` instead of `urllib`

**Comment by mehul-erpharbor** [comment]
not working
