### ISSUE TITLE
Research study Holistic Tabular View

### ISSUE THREAD

**Issue by habibieeddien** [pgbovine/OnlinePythonTutor#153]
I want to develop and research your idea of "[Holistic tabular view](https://github.com/pgbovine/OnlinePythonTutor/blob/master/v3/docs/project-ideas.md)", but I am having trouble finding a mental model of reference on Holistic Tabular view. Can you share this information? whether the existing research studies that with the tables students more easily understand the code and change-over the data?

I am very grateful for your help. Thanks.

**Comment by Seanny123** [comment]
You seem to be asking two separate questions:

1. How to implement Holistic Tabular view and what it would look like?
2. What research/experiences have informed the need for Holistic Tabular view?

Is this a correct interpretation of your questions?

**Comment by habibieeddien** [comment]
Yes, this is. Sorry for my english :)
So, Do you have some references for this research?

**Comment by Seanny123** [comment]
In the document he linked, he appears to have designed this based off of experiences he had in class, so I don't think any formal research has been done on this visualisation in particular.

**Comment by pgbovine** [comment]
Yep, Seanny123 is right ... i didn't explore this much beyond what i wrote in those online notes. good luck!
