### ISSUE TITLE
JavaScript backend: cannot use Date() object [Unable to use the object?]

### ISSUE THREAD

**Issue by yloveyy** [pgbovine/OnlinePythonTutor#154]
Like this:
var d ;
d = new Date();
console.log(d.getTime());

Can not run

Thanks

**Comment by pgbovine** [comment]
yikes, thanks for the bug report, i'll note this down! The minimal test case here for JavaScript is:

```
var d = new Date();
```

Weird that it doesn't work; I'll mark it down as a bug.

**Comment by chnt7305** [comment]
@pgbovine 
Thank you!

**Comment by pgbovine** [comment]
added to unsupported features doc and closed:
https://github.com/pgbovine/OnlinePythonTutor/blob/master/unsupported-features.md
