### ISSUE TITLE
Embed Python Tutor Editor on https page

### ISSUE THREAD

**Issue by baolocdo** [pgbovine/OnlinePythonTutor#155]
We would like to embed the PythonTutor editor (http://www.pythontutor.com/visualize.html#mode=edit) on our class website for students to use directly on the website and debug their code, especially in quizzes but it does not show up because our website requires https to fetch the page. Embedding the iframe with visualized code is ok since it is https. Can you please add support for https for www.pythontutor.com/visualize.html#mode=edit ? Thank you.

**Comment by pgbovine** [comment]
Sorry that leads to too much code duplication and maintenance at the moment. The iframe embedding works in https, though, but not regular python tutor.
