### ISSUE TITLE
python: duplicate intrinsic names

### ISSUE THREAD

**Issue by dannygoldstein** [pgbovine/OnlinePythonTutor#158]
[This](http://bit.ly/2bUR5yw) is a bit confusing. 

You can instantiate two functions on the heap with identical intrinsic names. It's difficult to tell which is which.

**Comment by pgbovine** [comment]
Can you give me an example using the "Generate permanent link" or "Generate shortened link" features at the bottom of the page? I don't quite get what you mean.

**Comment by pgbovine** [comment]
ah I see your link; sorry that probably won't be supported since it's not too common of an occurrence at the moment.
