### ISSUE TITLE
input box: Enter keypress doesn't submit (Python)

### ISSUE THREAD

**Issue by sogen** [pgbovine/OnlinePythonTutor#161]
Brief description: 
While using an input, pressing the Enter key to submit it, it doesn't submit the code, I have to use the mouse to Submit the entered text. 
This is different from the Terminal, where pressing Enter submits the entered text.

What am I trying to do:
After I enter some text, I press the **Enter key**, just like in any Python terminal.

Expected:
I expect that the entered text is submitted, like in Terminal.

What happens:
Nothing

Temporal solution:
I have to use the mouse to submit using the Submit button.

**Comment by pgbovine** [comment]
Thanks for your bug report, it's noted. I may not get around to implementing this, though, since in general I want to keep the keyboard bindings to a minimum for various reasons.
