### ISSUE TITLE
No scrollbar in Safari

### ISSUE THREAD

**Issue by sogen** [pgbovine/OnlinePythonTutor#162]
Hi, Safari 10 (El Capitan) shows no scrollbar, something like this in **opt-live.ts** about in line ~428 _ish_  should enable scrolling:

`$('#codeInputPane').css('overflow-y', 'scroll'); // To enable scrolling in Safari
`

so the compiled CSS should look like this:

```
div#codeInputPane.ace_editor.ace-tm.ui-resizable
width: 550px;
min-width: 250px;
max-width: 700px;
height: 420px;
overflow-y: scroll;
```

**Comment by pgbovine** [comment]
thanks for the tip! i'll check it out the next time i dive back into that codebase!
