### ISSUE TITLE
Request Python: Decorator Unitest

### ISSUE THREAD

**Issue by Suryadhulipudi** [pgbovine/OnlinePythonTutor#163]
Hi Team,

Can someone help me how to write test case for python decorator with a example?

Below one is the sample decorator:-

def test_tags(tags=""):
  """
  Test tags decorator. Does no modification to the test.

  Args:
    tags(str): String with CSV of tags.

  Returns:
    (object): The decorated callable.

  """
  def test_tags_args(functor):
    """
    Test tags args wrapper.
    """
    @wraps(functor)
    def wrapper(self, _args, *_kwargs):
      """
      Wrapper for the functor.
      """
      return functor(self, _args, *_kwargs)
    return wrapper
  return test_tags_args

**Comment by pgbovine** [comment]
This is not a forum for asking for help on Python.
