### ISSUE TITLE
Be friendlier to newbies in documentation link on main page

### ISSUE THREAD

**Issue by FlashSheridan** [pgbovine/OnlinePythonTutor#164]
The link in the “Details:” section of http://www.pythontutor.com for “View the project documentation online” points to a GitHub page.  Its first item is a biography of someone other than you, and its second item (“developer-overview.md”) is ambiguous between Python learners using the tutorial, and its actual target audience: experienced hackers.  I suspect your demographics include a lot of people starting to learn Python and unfamiliar with GitHub (you’re now linked in a number of Python books), so I suggest the main documentation link point to something aimed at Python learners.  

The text at http://www.pythontutor.com/visualize.html after the embedding instructions would be a good start:  it lists the supported Python versions and modules, followed by other languages.  But this text is sandwiched between other things, and is not very prominent.  I suggest calling it out, and having the main documentation link point to it.

**Comment by techtonik** [comment]
I bet people are clicking big "Start visualizing your code now" link rather than follow tiny links in detail. Perhaps just rename documentation to "technical paper" or "internal documetation".

**Comment by pgbovine** [comment]
Thanks for the suggestion, Flash! and sorry for my delay in attending to github issues; yes, i'll need to drastically revamp the docs someday :)

**Comment by pgbovine** [comment]
done
