### ISSUE TITLE
comments make "code too long"

### ISSUE THREAD

**Issue by iurisegtovich** [pgbovine/OnlinePythonTutor#165]
On [live mode]{http://www.pythontutor.com/live.html#mode=edit), 
the server refuses to run my code with the following warning:
    "Server error! Your code might be too long for this tool. Shorten your code and re-try."
I understand it is a cloud service and therefore we should not submit too long codes.
However, in my case the code is mainly #comments, because i was writing some Self-taught material.
Is it possible that your app would filter out the comment lines before taking a decision regarding the *code* being too long?
thanks in advance, you have an awesome app

**Comment by pgbovine** [comment]
good question, but sorry we cannot easily do this since we send all the code to the server to execute; please manually eliminate the comments in your code. good luck
