### ISSUE TITLE
Missing module

### ISSUE THREAD

**Issue by Vm900** [pgbovine/OnlinePythonTutor#172]
Hi folks,
Tried to it locally and got the following error:
Traceback (most recent call last):
  File "bottle_server.py", line 16, in <module>
    import StringIO # NB: don't use cStringIO since it doesn't support unicode!!!
ImportError: No module named 'StringIO'

Your help much appreciated

**Comment by pgbovine** [comment]
probably a python2 vs. python3 problem. try running python and seeing if StringIO exists, or io
