### ISSUE TITLE
Incomplete page load on Chrome Version 57.0.2987.110

### ISSUE THREAD

**Issue by Corinos** [pgbovine/OnlinePythonTutor#174]
Page only loads the first few elements
Tried clearing browser data, same issue
Tried using two different Chrome profiles (with different extensions), same issue
Loads on FF.
![image](https://cloud.githubusercontent.com/assets/10198853/24455374/a4226f94-1465-11e7-8793-869fecd583d2.png)

**Comment by pgbovine** [comment]
thanks! sorry for the delay -- i will look into https and certificate issues sometime

**Comment by pgbovine** [comment]
seems to work now!
