### ISSUE TITLE
HTTPS requests receive insecure responses, fail to load in Chrome

### ISSUE THREAD

**Issue by lizTheDeveloper** [pgbovine/OnlinePythonTutor#175]
A call to:
https://cokapi.com:8001/exec_js_jsonp?callback=jQuery30004714582724951575_1492638158780&user_script=var%20person%20%3D%20%7BfirstName%3A%20%22Alexander%22%7D%0Avar%20anotherPerson%20%3D%20person%3B%0A%0AanotherPerson.lastName%20%3D%20%22Hamilton%22%3B%0Aperson.motto%20%3D%20%22There%27s%20a%20million%20things%20I%20haven%27t%20done.%22%3B&options_json=%7B%22cumulative_mode%22%3Afalse%2C%22heap_primitives%22%3Afalse%2C%22show_only_outputs%22%3Afalse%2C%22origin%22%3A%22iframe-embed.js%22%7D&_=1492638158781

will return an insecure, plain HTTP response. This was fine until Chrome (as of a recent version, I'm at 57.0.2987.133) rejects the response and won't render embeds. I believe this is related to #174.

**Comment by pgbovine** [comment]
thanks! sorry for the delay -- i will look into https and certificate issues sometime

**Comment by pgbovine** [comment]
seems to work now!
