### ISSUE TITLE
Recursive Call not visualized

### ISSUE THREAD

**Issue by Schizo** [pgbovine/OnlinePythonTutor#177]
I was testing a recursive call:
```
def fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    return fibonacci(n-1) + fibonacci(n-2)
    
    
print fibonacci(10)
```

But this yields only an empty output, tested on 
http://www.pythontutor.com/live.html#mode=edit

**Comment by Sumukh** [comment]
FYI - this is because `fibonacci(10)`  takes too many steps (the limit is 1000 steps) - `fibonacci(9)` will work though since that only needs 524 steps :)
