### ISSUE TITLE
Linux startup script

### ISSUE THREAD

**Issue by wirepatch** [pgbovine/OnlinePythonTutor#181]
I've just updated from an older version which did not need thy python "bottle" server.
The docs mention the startup procedure. Unfortunately I could not find a hint towards a startup script with respect to host (re)boot.

I've hacked to simple start.sh and stop.sh scripts acting on behalf of a non-privileged user "bottle" on my system, see attached zip archive. The init.d script then calls these scripts during startup and shutdown.

Unfortunately my knowledge about the "bottle" server is quite limited and i.e. the "killall "usr/bin/python" call is a bit too simplistic.

I'd very much appreciate some hint in your documentation. Maybe even Systemd compliant? And sorry if I was just not digging deep enough.

Congratulations for your ongoing work!

**Comment by habibieeddien** [comment]
bottle server just for development on localhost, not recommended for production deployment. if you want to invoke, just run `python bottle_server.py`
don't forget to install `bottle` with `pip` before it.

maybe you forgot to attached zip archive.

**Comment by pgbovine** [comment]
thanks! sorry i don't have much time to work on the developer tooling around the project since i'm focused on running the site itself. good luck
