### ISSUE TITLE
Make visualisation more flexible/plugable  (ex., add PyAlgoViz style)

### ISSUE THREAD

**Issue by dz0** [pgbovine/OnlinePythonTutor#182]
in GH description it says "Visualize ..code execution" 
But now the visualization is quite text based, I found [PyAlgoViz](https://pyalgoviz.appspot.com/) ([YT intro](https://youtu.be/poQKuXgNd88?t=395)) which seems much more powerfull.

there is PyAlgoViz [repository](https://github.com/laffra/pyalgoviz/), but not sure if full engine is in there..

**Comment by dz0** [comment]
PyAlgoViz help says

```
Python Algorithm Visualization Help
--------------------------------------------------------------

The visualization script in the bottom left visualizes the code in the top left while it runs. You can refer to all local variables used in the algorithm above. 

The visualization script is executed once for each executed line in the algorithm. When the script runs, you can check the value of <b>__lineno__</b> to conditionally run a subset of your script to make the visualization act more like a breakpoint. 
You can include arbitrary Python code, including defining helper functions.

Available values/primitives:
 * __lineno__
 * beep(frequency, milliseconds)
 * text(x, y, txt, size=13, font='Arial', color='black')
 * line(x1, y1, x2, y2, color='black', width=1)
 * rect(x, y, w, h, fill='white', border='black')
 * circle(x, y, radius, fill='white', border='black')
 * arc(cx, cy, innerRadius, outerRadius, startAngle, endAngle, color='black')
 * barchart(x, y, w, h, items, highlight=-1, scale=1, 
```

**Comment by dz0** [comment]
ps.: If I have PyTutor traced data, probably it's not that hart to apply any js (or serverside) visualizations?

**Comment by catafest** [comment]
"
Python's main problem is that: it is a language with a specific target, a
certain set of supporters and scientific training.


2017-07-19 10:16 GMT+03:00 dz0 <notifications@github.com>:

**Comment by pgbovine** [comment]
not sure what actionable steps to take here, closing and archiving it in my private notes
