### ISSUE TITLE
Show which item in a list the code is looking at

### ISSUE THREAD

**Issue by willnwhite** [pgbovine/OnlinePythonTutor#183]
For example, I would like the [0][0] box to be highlighted here, because the code is on `if image[0][0]`: 
![screen shot 2017-08-08 at 12 46 45](https://user-images.githubusercontent.com/8081877/29070700-651e6f42-7c38-11e7-9fd8-276406b1c2ba.png)

**Comment by pgbovine** [comment]
great idea, but infeasible to do with the current backend tracing framework, unfortunately.

**Comment by Almenon** [comment]
Commenting on issues on a Sunday at Midnight?  Damn, that's some dedication.
