### ISSUE TITLE
Link directly to Python3 from PythonTutor.com

### ISSUE THREAD

**Issue by SuperAmin** [pgbovine/OnlinePythonTutor#186]
The link to Python directly links to Python 2. I think there should either be a link directly to Python.

Use case:
I'm teaching an intro to Python class where we're learning Python 3. It would be great to link directly to Python 3 visualization. The following link works, but it isn't listed anywhere on the main site.
http://www.pythontutor.com/visualize.html#py=3

**Comment by Almenon** [comment]
I agree, python 3 should be the default.  Python 2 will not be maintained past 2020

https://pythonclock.org/

**Comment by pgbovine** [comment]
Good suggestion, I'll try to update the links to have both Python 2 and 3 soon in the next update release
