### ISSUE TITLE
JavaScript: variables containing a dollar break printout

### ISSUE THREAD

**Issue by jtojnar** [pgbovine/OnlinePythonTutor#189]
I am trying to demonstrate execution of PHP code. Since PHP is not supported, I converted it to the following JavaScript code:

```
var $matice = [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
];

console.log('<table border="1">');
for (var $j = 0; $j < 3; $j++)
{
        console.log('<tr>');
        for (var $i = 0; $i < 3; $i++)
        {
                console.log('<td>' + $matice[$j][$i] + '</td>');
        }
        console.log('</tr>');
}
console.log('</table>');
```

Unfortunately, no text is added to the printout box and there is no arrow from the variable in the stack frame to the array object:

![image](https://user-images.githubusercontent.com/705123/33286313-50c4986c-d3b5-11e7-924c-86de5a2a680f.png)

The following message appears in the browser console:

    Error: Syntax error, unrecognized expression: #v1__global__$matice

When I remove the dollar signs, the execution works as expected.

**Comment by pgbovine** [comment]
interesting ... that's probably because $ isn't a legal character in CSS, which I'm using for the rendering styles. i should be able to fix this when I get the chance. very interesting use case, btw!

**Comment by pgbovine** [comment]
Note: this is actually recommended in the airbnb style guide, interesting:
https://github.com/airbnb/javascript#jquery--dollar-prefix

**Comment by pgbovine** [comment]
@jtojnar - fixed! check out https://goo.gl/465FFi (reload to clear browser cache)
