### ISSUE TITLE
Make a version of this as a Jupyter notebook extension

### ISSUE THREAD

**Issue by gramster** [pgbovine/OnlinePythonTutor#191]
That would be pretty cool.

**Comment by pgbovine** [comment]
I like that idea! But it's outside the scope of my project. I hope others take it on, though.

**Comment by iurisegtovich** [comment]
Hi, I made an ipython cell magic that encodes a cell content into an URL for pythontutor/live.

It is currently in my repo for lectures on programming in python and scipy (in Brasil' portuguese), [here](https://github.com/iurisegtovich/CursoSciPySEQ2018/tree/master/exemplos/python_notebooks).

Maybe we could suggest this python magic for the next ipython release.

There is a module with the magic command (`python_tutor_magic.py`) and a notebook with an example (`example_decimal_module_on_python_tutor.ipynb`).

**Comment by iurisegtovich** [comment]
I just found these:

>- https://pypi.org/project/tutormagic/
>- https://pypi.org/project/ipythontutor/
>- https://pypi.org/project/pytutor/
>- https://pypi.org/project/pvdb/
>- https://pypi.org/project/nbtutor/

didn't test them.
