### ISSUE TITLE
JavaScript backend: [let scoping bug?]

### ISSUE THREAD

**Issue by metasean** [pgbovine/OnlinePythonTutor#192]
In the JavaScript version, I've run into a really odd situation, which I'm pretty sure is a compiler bug.

In this [example code](http://pythontutor.com/live.html#code=let%20categoryList%20%3D%20%5B'tiger',%20'lion',%20'house'%5D%0A%20%20%0AcategoryList.forEach%28c%20%3D%3E%20%7B%0A%20%20console.log%28'outside%20of%20if',%20c%29%0A%7D%29%0A%0Aif%20%28categoryList%29%7B%0A%20%20let%20categories%20%3D%20'our%20categories%20are%3A'%0A%20%20%0A%20%20console.log%28'inside%20of%20the%20if'%29%0A%20%20%0A%20%20categoryList.forEach%28c%20%3D%3E%20%7B%0A%20%20%20%20console.log%28'in%20if',%20c%29%0A%20%20%20%20categories%20%2B%3D%20%60%24%7Bc%7D,%20%60%0A%20%20%7D%29%0A%20%20%0A%20%20console.log%28categories%29%0A%7D&cumulative=false&curInstr=11&heapPrimitives=false&mode=display&origin=opt-live.js&py=js&rawInputLstJSON=%5B%5D&textReferences=false) changing the  `let` to a `var` on line 8 makes the script work as expected.

**Comment by pgbovine** [comment]
Hmmm that's very interesting; I'll look into it! Thanks for the report.

**Comment by pgbovine** [comment]
fixed with https://github.com/pgbovine/OnlinePythonTutor/commit/2179495161245aad76f9b4df50095267fadd4077
