### ISSUE TITLE
(Feature request) More customisation of box-and-pointer diagrams

### ISSUE THREAD

**Issue by kaya3** [pgbovine/OnlinePythonTutor#195]
Thank you for this tool, especially the "live" mode - I have been using it as a presentation device, as well as recommending it to students. I would find it even more useful if there were more control over how the program state is rendered:

- Being able to hide classes and functions would avoid visual clutter - most classes don't have static members, and I can't think of many situations where somebody would want to monitor the dynamic state of a function.

- Rendering objects without nesting, while still keeping primitives inline, would be a good compromise between legibility and accuracy.

Both options would greatly help for teaching general principles rather than Python specifics.

**Comment by pgbovine** [comment]
i really like those suggestions! will look into them when i have time (but no guarantees since i don't have much time to update this project)

**Comment by pgbovine** [comment]
@kaya3 -- Can you clarify what you mean by: "Rendering objects without nesting, while still keeping primitives inline, would be a good compromise between legibility and accuracy."

Is there a simple example you could make to illustrate this point?

**Comment by kaya3** [comment]
I assume you mean an example of when nesting is insufficiently accurate, rather than an example of objects being drawn nested.

Context: I've been teaching reference semantics using box-and-pointer diagrams. I set exercises with some simple class definitions and a few lines of code, and asked students to draw box-and-pointer diagrams for the results. Afterwards, I showed them the Python Tutor live visualisation tool, but I had to warn them that its diagrams are not always correct box-and-pointer diagrams.

Nesting makes it appear that one object is "part of" another object, which could lead to (or reinforce) the misconception that a field holds the object itself rather than a reference to it. The tool appears to count references when deciding whether to nest an object; [for example, in this link](https://goo.gl/Ee2MkQ) the `Vector(1, 2)` is separate and the `Vector(3, 4)` is nested, but uncommenting the line `p = None` causes the `Vector(1, 2)` object to become nested. This is surprising, and could be confused for a feature of Python rather than the tool.

On the other hand, if I disable nesting then the diagram becomes overwhelmingly complicated due to all the pointers to primitive objects, and even the field names are pointers to string objects. That's a correct model of Python specifically, but not useful for teaching principles.

**Comment by pgbovine** [comment]
Thanks for the clarification! I will keep this in mind as I think about what rendering options to add. The trick is to do something reasonably useful and robust without cluttering up the UI with a combinatorial explosion of options (not to mention adding exponentially more paths for UI testing). I think both of your bullet points from the original thread are very reasonable, and I'll try to figure out a way to unify those options in an intuitive way in the coming months.

**Comment by pgbovine** [comment]
(just making a note for myself: besides hiding classes and functions by default, also hide python modules since those can get huge and are mostly meaningless)

**Comment by pgbovine** [comment]
(also note to self: think about how to "hide" functions -- maybe just display them inline in the global/stack frame like primitives, and just say "function". same with module/class/etc., when they're in abbreviated form. this way, the variables still exist, but their values aren't rendered on the heap, which saves space.)

**Comment by pgbovine** [comment]
(i also agree that the surprising "switch" from nested to non-nested is unintuitive ... i should think about how to make that consistent.)

**Comment by pgbovine** [comment]
@kaya3 -- your second suggestion has been implemented ... check out the new "inline primitives but don't nest objects" mode: https://goo.gl/Ahcjmr

the first suggestion is on my todo list under issuehttps://github.com/pgbovine/OnlinePythonTutor/issues/208

**Comment by kaya3** [comment]
That's awesome, thanks!

**Comment by pgbovine** [comment]
I'm closing this issue for now since many parts have been implemented; the remainder has been moved into this successor issue:
https://github.com/pgbovine/OnlinePythonTutor/issues/222
