### ISSUE TITLE
Java: make "render all objects on heap" the default

### ISSUE THREAD

**Issue by ChrisMayfield** [pgbovine/OnlinePythonTutor#200]
It makes sense why the "inline primitives & nested objects" option is default for Python, since all values are heap allocated. But for Java, it would be more helpful to see the difference between primitive and reference types every time (by default), especially for beginners.

**Comment by pgbovine** [comment]
That's an interesting observation. For historical reasons, the guy who made the Java backend (and also teaches extensively in Java) had that as the default, so I honored it. Note that options are "sticky" (saved in localStorage), so once you set it once for your machine, it will remain there next time.
