### ISSUE TITLE
SOS Python: AttributeError: 'str' object has no attribute 'readline' HELP! HELP!

### ISSUE THREAD

**Issue by AlinaPython** [pgbovine/OnlinePythonTutor#201]
Hi everyone,
I've recetly begun learning how to code on Python and due to lack of relevant experience, I often stuck in a simple because of Errors, which I can not find. I am sure it would be super easy for those who know how to code and confident with Python. I will highly appreciate if you can help me with code below:

def read_grades(gradefile):
    ''' (file, open for reading) -> list of float
    
    Read and return the list of grades in the gradefile.
    
    Precondition: Gradefile starts with a header that contains
    no blank lines, then has a blank line, and then lines
    containing a student number and a grade.
    '''
    # Skip over the header.
    line = gradefile.readline()
    while line != '\n':
        line = gradefile.readline()

    # Read the grades, accumulating them into a list.

    grades = []
    
    line = gradefile.readline()
    while line != '':
        # Now we have a string containing info for a single student.
        # Find the last space and take everything after that space.
        grade = line[line.rfind(' ') + 1:]
        grades.append(float(grade))
        line = gradefile.readline()

    return grades 
Attached is the file I am  trying  to read. After running module and reading the file, applying readline + while loop method, I have an Error:
Traceback (most recent call last):
  File "<pyshell#65>", line 1, in <module>
    read_grades(a1_histfilename)
  File "C:/Users/sergei/Desktop/PYTHON/developing program/grade.py", line 11, in read_grades
    line = a1_histfile.readline()
AttributeError: 'str' object has no attribute 'readline'

[grades.txt](https://github.com/pgbovine/OnlinePythonTutor/files/1803007/grades.txt)

Thank you very much for your help, it is my first time I am asking for support, pls text me if anything is unclear or you need any other details.

I am looking forward to seing my problem solved!

**Comment by pgbovine** [comment]
Please use the live help feature on the site where volunteers can help you. This is for reporting bugs on the site itself, not for getting help on programming questions.
