### ISSUE TITLE
rename entire service

### ISSUE THREAD

**Issue by extremelypenguin** [pgbovine/OnlinePythonTutor#202]
I don't understand why it's called _python_tutor if you can also visualize a whole bunch of other languages. I think we should rename the app

**Comment by pgbovine** [comment]
i'm totally with you. there's a lot of legacy reasons for this naming convention (i won't bore you with details), but i am well aware of this issue :) fwiw there are individual language tutor pages available, but they should probably go into their own domains later:

http://www.pythontutor.com/java.html#mode=edit
http://www.pythontutor.com/javascript.html#mode=edit
http://www.pythontutor.com/ruby.html#mode=edit
http://www.pythontutor.com/c.html#mode=edit
http://www.pythontutor.com/cpp.html#mode=edit

**Comment by extremelypenguin** [comment]
but if they went into their own domains then people might only hear about for example the python and not know that there are other languages supported. What are the legacy issues?
