### ISSUE TITLE
Visualization idea- Animations/ Gifs?

### ISSUE THREAD

**Issue by scottstanie** [pgbovine/OnlinePythonTutor#203]
I find this tool awesome to teach some programming concepts, but I found myself taking a screenshot of each step of an output in order to give a presentation using the visuals.
How difficult does it seem like it would be to have an "export images" or "create animation" button to capture each stage of the visualization to convert into a gif or slides?

**Comment by pgbovine** [comment]
Good idea. I'd highly recommend to use a browser automation tool like PhantomJS or the new Chrome automation tools to script this in a fairly straightforward way. (Adding this feature to the tool would clutter up the codebase and UI.)
