### ISSUE TITLE
emphasizing mutability and immmutaility

### ISSUE THREAD

**Issue by iurisegtovich** [pgbovine/OnlinePythonTutor#205]
Hi, I was trying to make a simple example to explain mutability and immutability. I came up with this:

```
a     =   0+0j
b     =   a
c     =   0+0j

print(id(a))
print(id(b))
print(id(c))

b+=2
c+=3

print(id(a))
print(id(b))
print(id(c))

la     =   [0,1,2]
lb     =   la
lc     =   [0,1,2]

print(id(la))
print(id(lb))
print(id(lc))

lb+=[4]
lc+=[5]

print(id(la))
print(id(lb))
print(id(lc))

```
[>. link](http://pythontutor.com/live.html#code=a%20%20%20%20%20%3D%20%20%200%2B0j%0Ab%20%20%20%20%20%3D%20%20%20a%0Ac%20%20%20%20%20%3D%20%20%200%2B0j%0A%0Aprint%28id%28a%29%29%0Aprint%28id%28b%29%29%0Aprint%28id%28c%29%29%0A%0Ab%2B%3D2%0Ac%2B%3D3%0A%0Aprint%28id%28a%29%29%0Aprint%28id%28b%29%29%0Aprint%28id%28c%29%29%0A%0Ala%20%20%20%20%20%3D%20%20%20%5B0,1,2%5D%0Alb%20%20%20%20%20%3D%20%20%20la%0Alc%20%20%20%20%20%3D%20%20%20%5B0,1,2%5D%0A%0Aprint%28id%28la%29%29%0Aprint%28id%28lb%29%29%0Aprint%28id%28lc%29%29%0A%0Alb%2B%3D%5B4%5D%0Alc%2B%3D%5B5%5D%0A%0Aprint%28id%28la%29%29%0Aprint%28id%28lb%29%29%0Aprint%28id%28lc%29%29&cumulative=false&curInstr=22&heapPrimitives=false&mode=display&origin=opt-live.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false)

and

```
a     =   0+0j
la    =   [1,2,3]

def f(x):
    x+=1
    return x

def g(x):
    x+=[4]
    return x
    
b=f(a)

lb=g(la)
```
[>.link](http://pythontutor.com/live.html#code=a%20%20%20%20%20%3D%20%20%200%2B0j%0Ala%20%20%20%20%3D%20%20%20%5B1,2,3%5D%0A%0Adef%20f%28x%29%3A%0A%20%20%20%20x%2B%3D1%0A%20%20%20%20return%20x%0A%0Adef%20g%28x%29%3A%0A%20%20%20%20x%2B%3D%5B4%5D%0A%20%20%20%20return%20x%0A%20%20%20%20%0Ab%3Df%28a%29%0A%0Alb%3Dg%28la%29&cumulative=false&curInstr=14&heapPrimitives=false&mode=display&origin=opt-live.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false)

I liked this example because the live programming mode shows b and c as arrows to the same block before incrementing;
and then as arrows to different blocks after incrementing because incrementing objects of immutable types creates a new object

However, this example with integers instead of complex doesn't show the nuance of b and c ever being two names to the same object, as the numbers just stay in the separate frames since the beginning.

I wonder why doesn't the python tutor / live programming use arrows for integer/float scalars, strings, logical and None as well.

Thank you for your attention

**Comment by pgbovine** [comment]
If you set the "inline primitives & nested objects [default]" option at the bottom of the page to "render all objects on the heap", that should do what you want. Good luck!

**Comment by iurisegtovich** [comment]
Hi!
That is perfect!
I should have seen it.
Thank you very much!
