### ISSUE TITLE
Can we try to build a OnlinePythonTutor plugin for SublimeText ?

### ISSUE THREAD

**Issue by vinaykumar2491** [pgbovine/OnlinePythonTutor#206]
Can we try to build a OnlinePythonTutor plugin for SublimeText or Atom etc...It would be absolutely awesome

**Comment by pgbovine** [comment]
This is a great idea but outside the current scope of the project. See here for more info:
https://github.com/pgbovine/OnlinePythonTutor/blob/master/unsupported-features.md

**Comment by Almenon** [comment]
I just ported [birdseye](https://github.com/alexmojaki/birdseye) to [VSCode](github.com/Almenon/birdseye-vscode) and it was pretty easy - I might take this on for VSCode if I have time.
