### ISSUE TITLE
Problem on webpack run

### ISSUE THREAD

**Issue by Anu1601CS** [pgbovine/OnlinePythonTutor#207]
@pgbovine Can you help me, please!
I am trying to run <code>npm run webpack</code> and i am getting this error 

![screenshot from 2018-03-25 19-14-48](https://user-images.githubusercontent.com/30978328/37990492-16dd4b80-3224-11e8-9a66-85c5a00409d2.png)

And please give a proper step to setup this on my local computer. I tried to install using <code>Readme file</code> but getting this error.

I need development environment so i can build or compile typescript files.
Thanks

**Comment by pgbovine** [comment]
Sorry it is outside the scope of this project for me to debug individual build errors on local machines; the only support I provide is for the pythontutor.com site itself.

**Comment by Anu1601CS** [comment]
@pgbovine Thanks
But, its important for me because of I am doing a project of college based on your <code>OnlinePythonTutor</code>. 
Only I want to <code>run web pack</code> to automatically recompile.

Please provide steps to install dependencies and version.
Please Thanks

**Comment by Anu1601CS** [comment]
@pgbovine Leave it.  
This issue is solved after spending  3 hours  :)

**Comment by HongSeokHwan** [comment]
@Anu1601CS Can you share your code or solution? I have same problem.
