### ISSUE TITLE
How to blacklist variables?

### ISSUE THREAD

**Issue by ebanner** [pgbovine/OnlinePythonTutor#212]
Is there a way to prevent some variables from being visualized via a blacklist?

For instance in the following example I would rather `data` not be displayed because it's an unimportant local variable and obfuscates `STACK` (which I would like to draw attention to).

![image](https://user-images.githubusercontent.com/2068912/39080753-e1a2c0d4-44e9-11e8-9dd3-f9a1917a1b6f.png)

I would love a "blacklist" section so I could put `data` in there and prevent it from showing up.

Thanks for the great project!

**Comment by pgbovine** [comment]
ignore_vars might work: https://www.youtube.com/watch?v=Mxt9HZWgwAM&list=PLzV58Zm8FuBL2WxxZKGZ6j1dH8NKb_HYI&index=6
