### ISSUE TITLE
Lots of ways of creating false sessions, and security flaws...

### ISSUE THREAD

**Issue by spdkils** [pgbovine/OnlinePythonTutor#213]
So, I've seen users abusing the fact you don't check many things when creating requests for help.

For example unusual username... (ASDF, just another user) etc.

In addition, they are injecting their own urls when you try and help someone. ( Gee that won't cause problems)

So, yeah... great site, but... you best start thinking about locking down some flaws.

**Comment by pgbovine** [comment]
Thanks! Some folks have emailed me about this recently as well. Will prioritize this soon. I guess that's a sign it's getting more popular :)

**Comment by pgbovine** [comment]
putting on my todo list and closing for now. thanks again
