### ISSUE TITLE
ugh, freegeoip geolocation API will be discontinued on 2018-07-01 ugh

### ISSUE THREAD

**Issue by pgbovine** [pgbovine/OnlinePythonTutor#214]
https://github.com/apilayer/freegeoip#readme

**Comment by marwahaha** [comment]
This might work as an alternative.. 
https://github.com/nekudo/shiny_geoip

P.S. Great talk today in Berkeley!

**Comment by pgbovine** [comment]
thanks!

**Comment by pgbovine** [comment]
migrated over to their successor API: https://ipstack.com/
