### ISSUE TITLE
Show function arguments in python visualisation

### ISSUE THREAD

**Issue by MaxNoe** [pgbovine/OnlinePythonTutor#220]
This would help a lot in explaining python's mutable default function arguments.

Consider this example:

```python
def f(a=[]):
    a.append(1)

f()
f()
```

It would be awesome if pythontutor showed something like

```
f(a=[]), f(a=[1]), f(a=[1, 1])
```
On the right side instead of just `f(a)`

**Comment by pgbovine** [comment]
yep, noted. it's kinda hard to get that info in the tracer, though, but i'll make a note of it

**Comment by pgbovine** [comment]
for reference on an older discussion of implementation ideas/details, see: https://github.com/pgbovine/OnlinePythonTutor/issues/127

**Comment by pgbovine** [comment]
closing for now and adding this to private notes; probably won't get implemented anytime soon, sorry!

**Comment by pgbovine** [comment]
re-opening --- this might help, but not sure yet!
https://docs.python.org/3/library/inspect.html#inspect.getfullargspec

**Comment by pgbovine** [comment]
@MaxNoe - fixed! https://t.co/d8iN1T5VJ8

**Comment by cdeil** [comment]
@pgbovine - This is awesome. Thank you!!!

I think the way it's implemented is that the function object holds a reference to the default argument list object, and there is no such reference from the global module namespace, right?
So the visualisation accurately reflects what is going on.

(@MaxNoe and I were teaching Python at a workshop, and there this question what happens with default mutable arguments came up.)

**Comment by pgbovine** [comment]
yep, there's no reference from the global module namespace
