### ISSUE TITLE
Inspired by "worrydream"

### ISSUE THREAD

**Issue by marwahaha** [pgbovine/OnlinePythonTutor#221]
I'm inspired by Bret Victor's [article on Learnable Programming](http://worrydream.com/LearnableProgramming/). There are some examples that seem appealing for PythonTutor, in particular the `Make meaning transparent` and `Make flow visible` sections. 

1. It would be exciting to have an English (or locale-specific) explanation as the code is visualized.
2. I'd love to mouse over a timeline and watch the code execute. I know you can click on a line of code and see which frames that line is run, but I would love to see some timeline graphic representing this across all lines of code.

Hope this is useful! If not, sorry to bother.

**Comment by pgbovine** [comment]
yep, noted! these represent much bigger changes that probably can't be implemented soon:
http://pgbovine.net/PG-Vlog-130-Python-Tutor-2018-bigger-feature-requests.htm
