### ISSUE TITLE
results are different between https://www.python.org/shell/ and http://pythontutor.com

### ISSUE THREAD

**Issue by liangbright** [pgbovine/OnlinePythonTutor#227]
x = 1.23
y = 1.23
print(id(x))
print(id(y))

run the above code on pythontutor
id(x) is the same as id(y)

run the above code on www.python.org/shell/ 
id(x) is different from id(y)

**Comment by pgbovine** [comment]
yep, that's an implementation issue, not an issue with the python language specification itself. different python interpreters are free to implement this semantics differently.
