### ISSUE TITLE
iframe embedding: interface not loading

### ISSUE THREAD

**Issue by liffiton** [pgbovine/OnlinePythonTutor#229]
I can't seem to get iframe embedding to work anywhere other than on the [pythontutor.com demo page](http://www.pythontutor.com/iframe-embed-demo.html).  Anywhere else, the exact same iframes (literally copied from that page) fail to load completely.  The HTML loads, the JS is fetched, and the JS appears to start executing, because it throws a single "unreachable code after return statement" warning in the console.  But no visualization interface ever appears.  With nothing else to go on in the console, I'm at a loss for what might be wrong.

For a demonstration, see https://chocolate-table.glitch.me/ (copied from the demo page with the relative iframe URLs turned into absolute URLs).

**Comment by pgbovine** [comment]
it might be an issue with glitch or https. (did you set the iframe embed link to https:// instead of http:// ?)

i can embed fine on a test page i created on my computer just now, so unfortunately i cannot reproduce your error.

**Comment by liffiton** [comment]
Ah, so the issue appears to be caused by blocking 3rd party cookies.  Everything, including that glitch demo site, works fine if the browser allows 3rd party cookies (tested in Firefox and Chrome).

Given that this is a standard, privacy-oriented preference in most browsers, could the iframe embed be made to work when it is enabled?  Or if that isn't possible, then it would be helpful if it at least presents an alert explaining why it isn't working, instead of a blank frame.

**Comment by pgbovine** [comment]
thanks for the note; i'll try to look into it later but don't have time at the moment.

**Comment by liffiton** [comment]
No problem.  I looked into it, and I think the fix should be relatively simple.

Both [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=536509#c79) and [Chrome](https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document) throw an exception when code tries to access `localStorage` if the 3rd party cookies preference is set.  In the iframe-embed JS code, that first seems to happen [here](https://github.com/pgbovine/OnlinePythonTutor/blob/0d2c867c585de021fd7c210a9219d79bcaab6ecf/v5-unity/js/opt-frontend-common.ts#L131).

The `supports_html5_storage()` function you have in there will properly return `false` if `localStorage` is not available due to the 3rd party preference.  Therefore, I think one very simple fix would be to move the entire conditional for the Safari workaround into the [`if (supports_html5_storage()) {`](https://github.com/pgbovine/OnlinePythonTutor/blob/0d2c867c585de021fd7c210a9219d79bcaab6ecf/v5-unity/js/opt-frontend-common.ts#L142) block.  Then, there would be no unprotected access of `localStorage` outside of a try block, and the exception will not break the page.

As far as I can tell, there are no other uses of `localStorage` in the iframe embed JS code, so I think that might be enough to fix the problem entirely.

Alternatively, because the Safari issue for which that workaround was created [appears to have been fixed](https://stackoverflow.com/a/23453866/7938656) as of Safari 11, you could possibly remove that workaround block altogether.  That would also result in all accesses to `localStorage` being protected by the call to `supports_html5_storage()`, but it would break things for the small number of people using an outdated version of Safari in private browsing mode.

I'd be happy to open a pull request if it would help.

**Comment by pgbovine** [comment]
thanks, mark! a pull request would be great for reference, but i may not end up using your final code since i might consider refactoring this portion quite a bit in the future. in any case, if you have time for it, that would be great, but otherwise your issue report is already fairly detailed so that i can look into it myself later.

**Comment by liffiton** [comment]
Pythontutor embedded in iframes now works for me in both Chromium and Firefox with 3rd-party cookies disabled.  Thanks!
