### ISSUE TITLE
an integer is a Python object, but it is not shown by PythonTutor

### ISSUE THREAD

**Issue by liangbright** [pgbovine/OnlinePythonTutor#230]
the code 'x = 1000" will be visualized as 
a global frame containing variable x and value 1000
and there is no object in the objects section

The visualization will give an impression that integers are not objects

**Comment by pgbovine** [comment]
turn on the "render all objects on the heap" option to get that behavior. (it's off by default because otherwise there will be way too many objects and pointers displayed on screen.)
