### ISSUE TITLE
Server error! Your code might be taking too much time/memory. Or the server CRASHED due to too many people using it.

### ISSUE THREAD

**Issue by pengcongfa** [pgbovine/OnlinePythonTutor#231]
When I run the v5 version of this project in the local docker, everything was deployed correctly and the live. html page could be accessed normally through IP and port (HTTP). However, when accessing the live.html page through the nginx reverse proxy, the function of the page cannot be used normally. The page always displays the following error:

`Server error! Your code might be taking too much time/memory. Or the server will be on the door
Due to too many people using it.`

What might be the reason for this?

**Comment by pgbovine** [comment]
sorry i don't currently provide support for local installations, only support for using the live site itself.
