### ISSUE TITLE
Allow users entering public help chat to view full chat history

### ISSUE THREAD

**Issue by chiamarc** [pgbovine/OnlinePythonTutor#234]
I sometimes find myself entering a chat and trying to get up to speed on the objective of the person who needs help.  It would be useful to see a scrollable (and expandable) chat log from the beginning of the request for help.

**Comment by pgbovine** [comment]
hi marc! first off, thanks for helping out. that's an interesting feature request; let me mull this over.

**Comment by pgbovine** [comment]
putting in my feature request notes and closing
