### ISSUE TITLE
Allow indentation with "cmd + [" or "cmd + ]" 

### ISSUE THREAD

**Issue by astaninger** [pgbovine/OnlinePythonTutor#235]

**Comment by pgbovine** [comment]
sorry i don't understand this bug report, can you send me an example using the "generate permanent link" feature?

**Comment by astaninger** [comment]
https://goo.gl/XVof26

**Comment by astaninger** [comment]
sorry for not being clear. It's not a bug, it's a feature request.

**Comment by pgbovine** [comment]
noted in wishlist document
