### ISSUE TITLE
can I see the value of java ArrayList, in the data visualization?

### ISSUE THREAD

**Issue by xu-song** [pgbovine/OnlinePythonTutor#236]
![screen shot 2018-09-18 at 10 03 52 am](https://user-images.githubusercontent.com/13825126/45660200-3068df80-bb2a-11e8-8d46-1b3bd445f081.png)

In the above case, this diagram only shows `java.util.ArrayList instance`. Why does it not show the value?

code can be found at https://goo.gl/PzvGcJ

**Comment by pgbovine** [comment]
sorry that is unsupported and will likely not be anytime soon due to implementation difficulties:
https://github.com/pgbovine/OnlinePythonTutor/blob/master/unsupported-features.md
