### ISSUE TITLE
code to url

### ISSUE THREAD

**Issue by liulu100** [pgbovine/OnlinePythonTutor#242]
I want to know how to  convert my python code to a url lie this:
 src="http://pythontutor.com/iframe-embed.html#code=x+%3D+5%0Ay+%3D+10%0Az+%3D+x+%2B+y&cumulative=false&py=2&curInstr=3

thank you!

**Comment by pgbovine** [comment]
use the button at the bottom of the visualizer to create an iframe embed URL
