### ISSUE TITLE
string visualization for C++

### ISSUE THREAD

**Issue by pinventado** [pgbovine/OnlinePythonTutor#256]
Is there a way to improve how strings are visualized for C++? This is how the [visualization](http://pythontutor.com/cpp.html#code=%23include%20%3Ciostream%3E%0Aint%20main%28%29%20%7B%0A%20%20std%3A%3Astring%20name%20%3D%20%22John%22%3B%0A%20%20std%3A%3Acout%20%3C%3C%20name%20%3C%3C%20%22%5Cn%22%3B%0A%20%20return%200%3B%0A%7D&curInstr=2&mode=display&origin=opt-frontend.js&py=cpp&rawInputLstJSON=%5B%5D) looks like right now.

I teach introductory programming using C++ and students love how PythonTutor helps them visualize their programs. However, it is intimidating and confusing when they see strings.

**Comment by pgbovine** [comment]
sorry, adding to this list here, not easy to support at the moment:
https://github.com/pgbovine/OnlinePythonTutor/blob/master/unsupported-features.md
