### ISSUE TITLE
configure: error: please use gcc >= 3.0 or clang >= 2.9 or icc >= 13.0

### ISSUE THREAD

**Issue by malavancs** [pgbovine/OnlinePythonTutor#260]
When I run `make` for c_cpp backend. I get this error.

**Comment by pgbovine** [comment]
sorry local installation and configuration is not supported; i can only provide support for bugs reported on the python tutor site itself

**Comment by malavancs** [comment]
I figure out the problem by the way. I lowered the ubuntu version to 16.04 LTS. It works fine on that.
