### ISSUE TITLE
webpack problem

### ISSUE THREAD

**Issue by guangyaw** [pgbovine/OnlinePythonTutor#266]
[log.txt](https://github.com/pgbovine/OnlinePythonTutor/files/3161571/log.txt)

Sorry , I try to run webpack .  But meet the error as attached file called log.txt.
some of the error is the path problem .(ex: qtip , ace, ..., I try to fix them but fail).
Could you have some suggestion for me to fix the errors?

Below is the package.json of mine for your reference.
[package.json.txt](https://github.com/pgbovine/OnlinePythonTutor/files/3161588/package.json.txt)

**Comment by pgbovine** [comment]
sorry i don't have the time to provide tech support for local installations:
https://github.com/pgbovine/OnlinePythonTutor/blob/master/unsupported-features.md
