### ISSUE TITLE
Python3.6: wrong result displayed

### ISSUE THREAD

**Issue by vpoulailleau** [pgbovine/OnlinePythonTutor#275]
Here is a sample program that doesn't display the right result:

```python
a = 123456789
b = 123456789
print(a is b)
```

This displays `True` in OnlinePythonTutor, but not in the REPL (with CPython):

```python
$  python3.6
Python 3.6.8 (default, Aug 20 2019, 17:12:48) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> a = 123456789
>>> b = 123456789
>>> print(a is b)
False
```

I don't know why, but it screwed my demo ;-)

BTW, thanks for your OnlinePythonTutor which is great.

**Comment by pgbovine** [comment]
id() and 'is' behavior is a CPython implementation detail, not part of the language spec, especially for teaching beginners. so in general this behavior isn't guaranteed to be consistent across implementations.

**Comment by vpoulailleau** [comment]
There are implementations details. A CPython implementation detail is the fact that CPython use the address of the object as the id. But `id()` and `is` is part of the language spec (for instance https://docs.python.org/3/library/functions.html#id or https://docs.python.org/3/reference/expressions.html#comparisons). Another implementation detail is that CPython pre-allocates the  first integers (-5 to 256 https://docs.python.org/3/c-api/long.html#c.PyLong_FromLong) to avoid frequent re-allocation of commonly used integers, so some integers might keep their IDs in CPython, that's the reason why I chose a "huge" number in my example. I do agree that `id()` implementation isn't guaranteed to be consistent across implementation, but CPython is so commonly used.

@pgbovine I finally got the answer I wanted, here: https://github.com/pgbovine/OnlinePythonTutor/issues/255#issuecomment-482791529 due to another implementation detail of CPython that I didn't know, which explains two different behaviors of CPython depending on the usage…

And for future readers, check https://github.com/pgbovine/OnlinePythonTutor/blob/aa6284f2d1fec82d0e739efcc54cec4e601b65b8/unsupported-features.md#python
