### ISSUE TITLE
javascript - variables declared with let are not named correctly in graphic show

### ISSUE THREAD

**Issue by Ieahleen** [pgbovine/OnlinePythonTutor#283]
Variables declared with let that are not declared globally have all this issue.
Example: 
instead of having the `result` variable, there is `n (block 1)`

![4AA78D59-E89D-4CF3-A82E-3DCECF73830A](https://user-images.githubusercontent.com/26656284/68923483-bad4bf80-077e-11ea-8582-7ca4ad166c0b.jpeg)

I often suggest this tool to newbies, but a thing like this is greatly confusing

**Comment by pgbovine** [comment]
thanks for this bug report! i don't have time now to investigate but have added it to the list of todos

**Comment by pgbovine** [comment]
fixed https://github.com/pgbovine/OnlinePythonTutor/commit/2179495161245aad76f9b4df50095267fadd4077
