### ISSUE TITLE
Want to do some translation to Chinese on the instance webpage, can you advise the code structure in a bit detail?

### ISSUE THREAD

**Issue by wrenashe** [pgbovine/OnlinePythonTutor#284]
Want to do some translation to Chinese on the instance webpage, can you advise the code structure in a bit detail?

Thanks, by the way, for such a brilliant contribution online.

**Comment by pgbovine** [comment]
https://github.com/pgbovine/OnlinePythonTutor/blob/master/unsupported-features.md
