### ISSUE TITLE
modify one of the two variables but having both of them change their value

### ISSUE THREAD

**Issue by grasshelicopter** [pgbovine/OnlinePythonTutor#287]
in my code using C, i use a nested structure that is _person_name_:
```
struct person_name{
    char first[FIRST_NAME_LEN+1];
    char middle_initial;
    char last[LAST_NAME_LEN+1];
};
```
and a _student_ structure data type which include _person_name_ structure data type, after that i declare two variable _student1_ and _student2_ with a _student_ data type.
```
    struct student{
        struct person_name name;
        int id,age;
        char sex;
    }student1,student2;
``` 
in my following program, i modify _student1_:
```
    memcpy(student1.name.first,"Fred",sizeof("Fred"));
    student1.name.middle_initial = 'C';
    strcpy(student1.name.last,"Yay");
    display_name(student1.name);
}
```
i only modify one of two variable i.e. _student1_, but in pythontutor, both of them having the same value. 

<img width="949" alt="Annotation 2019-12-13 101308" src="https://user-images.githubusercontent.com/50168588/70764032-31baa380-1d91-11ea-8263-9fb8960f93d9.png">

**Comment by pgbovine** [comment]
interesting ... i'll investigate later on

**Comment by pgbovine** [comment]
closed and moved to https://github.com/pgbovine/opt-cpp-backend/issues/84
