### ISSUE TITLE
Let and const variables are off in visualizer

### ISSUE THREAD

**Issue by danny-byrne** [pgbovine/OnlinePythonTutor#288]
As you can see most obviously in this example,  rIdx is actually showing tmpResults.  Everything seems to be one off.  Also, having 'let' declarations be displayed as (block1, 2, 3...) and so on is incredibly annoying, why not just have the memory space name?

![Screen Shot 2019-12-29 at 11 29 41 AM](https://user-images.githubusercontent.com/27739300/71561727-0ab9ce00-2a2f-11ea-9fb1-a884bc0d7b64.png)

**Comment by danny-byrne** [comment]
link is here: 

[http://pythontutor.com/visualize.html#code=function%20stringPermutations%28str%29%20%7B%0A%20%20%20%20let%20letters%20%3D%20str.split%28''%29%3B%0A%20%20%20%20let%20results%20%3D%20%5B%5Bletters.shift%28%29%5D%5D%20%0A%20%20%20%20while%20%28letters.length%29%20%7B%0A%20%20%20%20%20%20%20%20const%20currLetter%20%3D%20letters.shift%28%29%0A%20%20%20%20%20%20%20%20let%20tmpResults%20%3D%20%5B%5D%0A%20%20%20%20%20%20%20%20//%20results.forEach%28%28result%29%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20for%28let%20result%20of%20results%29%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20let%20rIdx%20%3D%200%0A%20%20%20%20%20%20%20%20%20%20%20%20while%20%28rIdx%20%3C%3D%20result.length%29%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20const%20tmp%20%3D%20%5B...result%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20tmp.splice%28rIdx,%200,%20currLetter%29%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20tmpResults.push%28tmp%29%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20rIdx%2B%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20results%20%3D%20tmpResults%0A%20%20%20%20%7D%0A%20%20%20%20return%20results%0A%20%20%20%20%20%20.map%28letterArray%20%3D%3E%20letterArray.join%28''%29%29%0A%20%20%20%20%20%20.filter%28%28el,%20idx,%20self%29%20%3D%3E%20%28self.indexOf%28el%29%20%3D%3D%3D%20idx%29%29%0A%20%20%20%20%20%20.sort%28%29%0A%7D%0A%0Aconsole.log%28stringPermutations%28'cat'%29%29%3B&cumulative=false&curInstr=0&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=js&rawInputLstJSON=%5B%5D&textReferences=false](url)

**Comment by pgbovine** [comment]
Thanks for the bug report! This is something I want to get around to fixing, but just haven't had time yet. If you have other minimal test cases that expose similar issues, please add them to this thread.

**Comment by pgbovine** [comment]
also note to self: instead of displaying "block 1" etc., display the line on which each let-defined variable was defined. (memory addresses differ between executions, so it's harder to match up traces for other uses, etc.)

**Comment by pgbovine** [comment]
fixed the "off-by-one" problem so all the let-defined variables should now print correctly. commit https://github.com/pgbovine/OnlinePythonTutor/commit/2179495161245aad76f9b4df50095267fadd4077

however, there's still a duplicate for for-loop variables, which doesn't have an easy fix at the moment, and i don't have time to look more into it: https://github.com/pgbovine/OnlinePythonTutor/issues/264
