### ISSUE TITLE
Need help in connecting local Anaconda Backend

### ISSUE THREAD

**Issue by ravish0007** [pgbovine/OnlinePythonTutor#293]
I mostly operate my routines offline, I would like to know if I can tweak to use personal computer's Anaconda.

If not possible, docker with anaconda can act as a backend, will be very beneficial,

Thanks

**Comment by pgbovine** [comment]
https://github.com/pgbovine/OnlinePythonTutor/blob/master/unsupported-features.md

**Comment by ravish0007** [comment]
guess I have to dig up the whole base then, Anyway Thank you, I really appreciate what you hace done with this project
