### ISSUE TITLE
Any way as of now to run the visualiser for C code locally?

### ISSUE THREAD

**Issue by humanitiesclinic** [pgbovine/OnlinePythonTutor#300]
Any way as of now to run the visualiser for C code locally?

I understand the code on Github is currently only for Python. May I know if there's any way to get the code for C, because I need it to visualise a program as large as 10000 lines, and I am having a code too long error if I use the web interface...

**Comment by Young236** [comment]
I have the same problem with you

**Comment by pgbovine** [comment]
https://github.com/pgbovine/OnlinePythonTutor/blob/master/unsupported-features.md
