### ISSUE TITLE
User input is not supported in vs code

### ISSUE THREAD

**Issue by Mshorafa** [pgbovine/OnlinePythonTutor#304]
This is my code I try it on the online web works fine but in vs code git me an error "User input is not supported"
import random

m = random.randint(1, 5)
x = int(input("number : "))

if m != x:
    print(f"X = {x} and m = {m}")
else:
    print(f"X = {x} and m = {m}")
<img width="1680" alt="Screen Shot 2020-05-08 at 5 19 55 AM" src="https://user-images.githubusercontent.com/25303790/81363253-8cabb900-90eb-11ea-8a37-b3dcb2481219.png">
How can I solve this ?

**Comment by pgbovine** [comment]
https://github.com/pgbovine/OnlinePythonTutor/blob/master/unsupported-features.md
