### ISSUE TITLE
turtle module interface to HTML5 graphics 

### ISSUE THREAD

**Issue by dz0** [pgbovine/OnlinePythonTutor#46]
for beginners  turtle graphics addin would be also nice :)

Andrea Roberge had idea for Crunchy:
http://code.google.com/p/crunchy/source/browse/trunk/crunchy/src/imports/turtle_js.py

which interfaces javascript by emiting js commands for canvas drawing...
Now there are some better apis of javascript turtle -- so easier to interface, for example
http://code.google.com/p/canto-js/source/browse/trunk/canto.js 
https://github.com/davebalmer/turtlewax

so, by stepping forward one could also track the drawing (stepping backwards might be inapropriate..)

**Comment by pgbovine** [comment]
sorry this is out of scope for now
