### ISSUE TITLE
Permanent links include parens from code, making linking in Markdown difficult.

### ISSUE THREAD

**Issue by Widdershin** [pgbovine/OnlinePythonTutor#91]
When using the Generate Permanent Link button on the Visualizer, it will return URLs containing parens.

For example, this program:

    def foo():
        print('bar')

Returns this URL:

http://pythontutor.com/visualize.html#code=def+foo()%3A%0A++++print('bar')&mode=display&origin=opt-frontend.js&cumulative=false&heapPrimitives=false&drawParentPointers=false&textReferences=false&showOnlyOutputs=false&py=2&rawInputLstJSON=%5B%5D&curInstr=0

The URL works, but it is hard to link to on Reddit because the Markdown link syntax uses parens to enclose the URL. This problem can be solved by replacing parens with their URL escaped equivalents ('(' becomes %28, ')' becomes %29).

Github is smart enough to deal with this problem, but Reddit isn't. (I was really hoping Github would also have this issue and demonstrate my point, but alas).

I noticed this come up when someone attempted to [link to a Python Tutor visualization on Reddit](http://www.reddit.com/r/learnpython/comments/2j20kw/i_dont_understand_calls_and_passes/cl7n1w0).

I think this probably isn't very important, but I feel changing to escaped URLs will provide a more trouble free experience all round. Feel free to close this if you think Reddit should just have smarter markdown parsing.

**Comment by pgbovine** [comment]
done!
