### ISSUE TITLE
Use heuristics to auto-detect whether code is more likely to be Python 2 or 3

### ISSUE THREAD

**Issue by pgbovine** [pgbovine/OnlinePythonTutor#95]
and pop up a suggestion for the user

**Comment by asweigart** [comment]
I had actually started up a git repo to make a module that does exactly this (though I haven't had time to do an implementation yet): https://github.com/asweigart/detect2or3

This is a feature that I'd like to have in a redesign of IDLE, so I'd be willing to help with this issue.

**Comment by pgbovine** [comment]
getting to be a moot point for now as the majority of users are on py3 now. long live py3!
